"""Generate 20260402103050_team_collaboration_ledger_core.sql"""
import re
from pathlib import Path

root = Path(__file__).resolve().parents[2]
schema = (root / "supabase" / "schema.sql").read_text(encoding="utf-8")

NAMES = [
    "create_transaction_internal",
    "delete_transaction_internal",
    "update_transaction",
    "get_dashboard_summary",
    "delete_account_cascade",
    "add_savings_progress",
    "update_savings_goal",
    "refund_savings_progress",
    "run_due_recurring_transactions",
    "mark_bill_paid",
    "create_loan",
    "update_loan",
    "record_loan_payment",
    "delete_loan_cascade",
    "exchange_account_currency",
]


def extract_function(name: str) -> str:
    needle = f"create or replace function public.{name}("
    starts = [m.start() for m in re.finditer(re.escape(needle), schema)]
    if not starts:
        raise SystemExit(f"missing {name}")
    start = starts[-1]
    rest = schema[start:]
    m = re.search(r"\n\$\$;\n", rest)
    if not m:
        raise SystemExit(f"unterminated {name}")
    return rest[: m.end()]


def patch(name: str, src: str) -> str:
    if name == "delete_account_cascade":
        return src.replace(
            """  if v_user_id <> auth.uid() then
    raise exception 'Forbidden';
  end if;""",
            """  if p_organization_id is null then
    if v_user_id <> auth.uid() then
      raise exception 'Forbidden';
    end if;
  elsif public.organization_actor_role(p_organization_id, auth.uid()) not in ('owner', 'co_owner', 'admin') then
    raise exception 'Forbidden';
  end if;""",
        )

    if name == "delete_loan_cascade":
        return src.replace(
            """  v_user_id := auth.uid();
  if v_user_id is null then
    raise exception 'Unauthorized';
  end if;

  select l.principal_transaction_id""",
            """  v_user_id := auth.uid();
  if v_user_id is null then
    raise exception 'Unauthorized';
  end if;

  if p_organization_id is not null then
    perform public.assert_org_owner_or_co_owner_may_delete(p_organization_id);
  end if;

  select l.principal_transaction_id""",
        )

    if "p_user_id uuid" not in src:
        return src

    head = src.split("as $$", 1)[0] + "as $$"
    body = src.split("as $$", 1)[1]

    if "v_sub uuid" not in body:
        if "declare" in body:
            body = body.replace("declare\n", "declare\n  v_sub uuid;\n", 1)
        else:
            # e.g. exchange_account_currency: as $$ then begin (no declare)
            body = body.replace("begin\n", "declare\n  v_sub uuid;\nbegin\n", 1)

    if "perform public.assert_workspace_access(p_user_id, p_organization_id);" in body:
        body = body.replace(
            "perform public.assert_workspace_access(p_user_id, p_organization_id);",
            "perform public.assert_workspace_access(p_user_id, p_organization_id);\n"
            "  v_sub := public.workspace_row_subject_user_id(p_user_id, p_organization_id);",
            1,
        )
    elif "perform public.assert_workspace_read(p_user_id, p_organization_id);" in body:
        body = body.replace(
            "perform public.assert_workspace_read(p_user_id, p_organization_id);",
            "perform public.assert_workspace_read(p_user_id, p_organization_id);\n"
            "  v_sub := public.workspace_row_subject_user_id(p_user_id, p_organization_id);",
            1,
        )

    if name == "delete_transaction_internal":
        body = body.replace(
            "v_sub := public.workspace_row_subject_user_id(p_user_id, p_organization_id);",
            "v_sub := public.workspace_row_subject_user_id(p_user_id, p_organization_id);\n"
            "  if p_organization_id is not null then\n"
            "    perform public.assert_org_owner_or_co_owner_may_delete(p_organization_id);\n"
            "  end if;",
            1,
        )

    for pat in (
        "and user_id = p_user_id",
        "and t.user_id = p_user_id",
        "and a.user_id = p_user_id",
        "and c.user_id = p_user_id",
        "and l.user_id = p_user_id",
        "and lp.user_id = p_user_id",
        "and g.user_id = p_user_id",
        "and r.user_id = p_user_id",
    ):
        body = body.replace(pat, pat.replace("p_user_id", "v_sub"))

    body = body.replace("where user_id = p_user_id\n", "where user_id = v_sub\n")

    body = body.replace(
        ") values (\n    p_user_id,\n    p_organization_id,",
        ") values (\n    v_sub,\n    p_organization_id,",
    )
    body = re.sub(
        r"perform public\.create_transaction\(\s*\n\s*p_user_id,",
        "perform public.create_transaction(\n      v_sub,",
        body,
    )

    return head + body


out = ["-- Generated by gen_team_ledger_core.py\n"]
for n in NAMES:
    out.append(patch(n, extract_function(n)))

mig = (root / "supabase" / "migrations" / "20260330130000_delete_savings_goal.sql").read_text(encoding="utf-8")
ds = mig.split("create or replace function public.delete_savings_goal", 1)[1]
ds = "create or replace function public.delete_savings_goal" + ds.split("grant ", 1)[0].strip()
if not ds.endswith("$$;"):
    ds = ds.rsplit("$$", 1)[0] + "$$;"
ds = ds.replace(
    """declare
  v_current numeric;
begin
  if auth.uid() is null or auth.uid() <> p_user_id then
    raise exception 'Unauthorized';
  end if;

  perform public.assert_workspace_access(p_user_id, p_organization_id);""",
    """declare
  v_current numeric;
  v_sub uuid;
begin
  if auth.uid() is null then
    raise exception 'Unauthorized';
  end if;

  perform public.assert_workspace_access(p_user_id, p_organization_id);
  v_sub := public.workspace_row_subject_user_id(p_user_id, p_organization_id);
  if p_organization_id is not null then
    perform public.assert_org_owner_or_co_owner_may_delete(p_organization_id);
  end if;""",
)
ds = ds.replace("and user_id = p_user_id", "and user_id = v_sub")
out.append(ds)
out.append("\n")

Path(root / "supabase" / "migrations" / "20260402103050_team_collaboration_ledger_core.sql").write_text(
    "".join(out),
    encoding="utf-8",
)
print("wrote ledger core")
