-- Generated by gen_team_ledger_core.py
create or replace function public.create_transaction_internal(
  p_user_id uuid,
  p_account_id uuid,
  p_category_id uuid,
  p_kind text,
  p_amount numeric,
  p_transaction_date timestamptz,
  p_note text,
  p_transfer_account_id uuid,
  p_transfer_credit_amount numeric default null,
  p_source_type text default null,
  p_source_ref_id uuid default null,
  p_organization_id uuid default null
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_sub uuid;
  v_id uuid;
  v_credit numeric;
  v_category_type text;
  v_source_currency text;
  v_source_balance numeric;
  v_dest_currency text;
  v_normalized_source_type text;
begin
  perform public.assert_workspace_access(p_user_id, p_organization_id);
  v_sub := public.workspace_row_subject_user_id(p_user_id, p_organization_id);

  if p_amount is null or p_amount <= 0 then
    raise exception 'Amount must be positive';
  end if;

  if p_kind not in ('income', 'expense', 'transfer') then
    raise exception 'Invalid transaction kind';
  end if;

  select upper(trim(coalesce(a.currency_code, ''))), a.current_balance
  into v_source_currency, v_source_balance
  from public.accounts a
  where a.id = p_account_id
    and a.user_id = v_sub
    and public.workspace_matches(a.organization_id, p_organization_id);

  if v_source_currency is null or v_source_currency = '' then
    raise exception 'Account not found';
  end if;

  v_normalized_source_type := nullif(lower(trim(coalesce(p_source_type, ''))), '');
  if v_normalized_source_type is not null
     and v_normalized_source_type not in (
       'savings_contribution',
       'savings_refund',
       'loan_principal',
       'loan_payment'
     ) then
    raise exception 'Invalid transaction source';
  end if;

  if (v_normalized_source_type is null and p_source_ref_id is not null)
     or (v_normalized_source_type is not null and p_source_ref_id is null) then
    raise exception 'Transaction source reference mismatch';
  end if;

  if p_kind = 'transfer' then
    if p_transfer_account_id is null or p_transfer_account_id = p_account_id then
      raise exception 'Invalid transfer accounts';
    end if;

    if p_category_id is not null then
      raise exception 'Transfers cannot use categories';
    end if;

    select upper(trim(coalesce(a.currency_code, '')))
    into v_dest_currency
    from public.accounts a
    where a.id = p_transfer_account_id
      and a.user_id = v_sub
      and public.workspace_matches(a.organization_id, p_organization_id);

    if v_dest_currency is null or v_dest_currency = '' then
      raise exception 'Transfer account not found';
    end if;

    if v_source_currency <> v_dest_currency then
      if p_transfer_credit_amount is null or p_transfer_credit_amount <= 0 then
        raise exception 'Cross-currency transfer requires a converted destination amount';
      end if;
    end if;

    v_credit := coalesce(p_transfer_credit_amount, p_amount);
    if v_credit <= 0 then
      raise exception 'Invalid transfer credit amount';
    end if;

    if coalesce(v_source_balance, 0) < p_amount then
      raise exception 'Insufficient balance in source account';
    end if;
  else
    if p_category_id is not null then
      select c.type
      into v_category_type
      from public.categories c
      where c.id = p_category_id
        and c.user_id = v_sub
        and public.workspace_matches(c.organization_id, p_organization_id);

      if v_category_type is null then
        raise exception 'Category not found';
      end if;

      if v_category_type <> p_kind then
        raise exception 'Category type must match transaction kind';
      end if;
    end if;

    v_credit := null;

    if p_kind = 'expense' and coalesce(v_source_balance, 0) < p_amount then
      raise exception 'Insufficient balance in account';
    end if;
  end if;

  insert into public.transactions (
    user_id,
    organization_id,
    account_id,
    category_id,
    kind,
    amount,
    transfer_credit_amount,
    source_type,
    source_ref_id,
    note,
    transaction_date,
    transfer_account_id
  ) values (
    v_sub,
    p_organization_id,
    p_account_id,
    case when p_kind = 'transfer' then null else p_category_id end,
    p_kind,
    p_amount,
    case when p_kind = 'transfer' then v_credit else null end,
    v_normalized_source_type,
    p_source_ref_id,
    p_note,
    coalesce(p_transaction_date, now()),
    p_transfer_account_id
  ) returning id into v_id;

  if p_kind = 'expense' then
    update public.accounts
    set current_balance = current_balance - p_amount
    where id = p_account_id
      and user_id = v_sub
      and public.workspace_matches(organization_id, p_organization_id);
  elsif p_kind = 'income' then
    update public.accounts
    set current_balance = current_balance + p_amount
    where id = p_account_id
      and user_id = v_sub
      and public.workspace_matches(organization_id, p_organization_id);
  else
    update public.accounts
    set current_balance = current_balance - p_amount
    where id = p_account_id
      and user_id = v_sub
      and public.workspace_matches(organization_id, p_organization_id);

    update public.accounts
    set current_balance = current_balance + v_credit
    where id = p_transfer_account_id
      and user_id = v_sub
      and public.workspace_matches(organization_id, p_organization_id);
  end if;

  return v_id;
end;
$$;
create or replace function public.delete_transaction_internal(
  p_user_id uuid,
  p_transaction_id uuid,
  p_allow_linked boolean default false,
  p_organization_id uuid default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_sub uuid;
  r record;
  v_credit numeric;
begin
  perform public.assert_workspace_access(p_user_id, p_organization_id);
  v_sub := public.workspace_row_subject_user_id(p_user_id, p_organization_id);
  if p_organization_id is not null then
    perform public.assert_org_owner_or_co_owner_may_delete(p_organization_id);
  end if;

  select *
  into r
  from public.transactions
  where id = p_transaction_id
    and user_id = v_sub
    and public.workspace_matches(organization_id, p_organization_id);

  if not found then
    raise exception 'Transaction not found';
  end if;

  if not p_allow_linked and r.source_type is not null then
    raise exception 'This transaction is managed from its original feature and cannot be deleted here';
  end if;

  if r.kind = 'expense' then
    update public.accounts
    set current_balance = current_balance + r.amount
    where id = r.account_id
      and user_id = v_sub
      and public.workspace_matches(organization_id, p_organization_id);
  elsif r.kind = 'income' then
    update public.accounts
    set current_balance = current_balance - r.amount
    where id = r.account_id
      and user_id = v_sub
      and public.workspace_matches(organization_id, p_organization_id);
  elsif r.kind = 'transfer' then
    v_credit := coalesce(r.transfer_credit_amount, r.amount);
    update public.accounts
    set current_balance = current_balance + r.amount
    where id = r.account_id
      and user_id = v_sub
      and public.workspace_matches(organization_id, p_organization_id);
    update public.accounts
    set current_balance = current_balance - v_credit
    where id = r.transfer_account_id
      and user_id = v_sub
      and public.workspace_matches(organization_id, p_organization_id);
  end if;

  delete from public.transactions
  where id = p_transaction_id
    and user_id = v_sub
    and public.workspace_matches(organization_id, p_organization_id);
end;
$$;
create or replace function public.update_transaction(
  p_user_id uuid,
  p_transaction_id uuid,
  p_amount numeric,
  p_category_id uuid,
  p_note text,
  p_transfer_credit_amount numeric default null,
  p_organization_id uuid default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_sub uuid;
  r record;
  v_old_credit numeric;
  v_new_credit numeric;
  v_bal numeric;
  v_dest_bal numeric;
  v_cat text;
  v_src_cur text;
  v_dst_cur text;
begin
  perform public.assert_workspace_access(p_user_id, p_organization_id);
  v_sub := public.workspace_row_subject_user_id(p_user_id, p_organization_id);

  select *
  into r
  from public.transactions
  where id = p_transaction_id
    and user_id = v_sub
    and public.workspace_matches(organization_id, p_organization_id);

  if not found then
    raise exception 'Transaction not found';
  end if;

  if r.source_type is not null then
    raise exception 'This transaction is managed from its original feature and cannot be edited here';
  end if;

  if p_amount is null or p_amount <= 0 then
    raise exception 'Amount must be positive';
  end if;

  if r.kind <> 'transfer' then
    if p_category_id is not null then
      select c.type
      into v_cat
      from public.categories c
      where c.id = p_category_id
        and c.user_id = v_sub
        and public.workspace_matches(c.organization_id, p_organization_id);
      if v_cat is null then
        raise exception 'Category not found';
      end if;
      if v_cat <> r.kind then
        raise exception 'Category type must match transaction kind';
      end if;
    end if;
  end if;

  if r.kind = 'expense' then
    select a.current_balance into v_bal
    from public.accounts a
    where a.id = r.account_id
      and a.user_id = v_sub
      and public.workspace_matches(a.organization_id, p_organization_id);
    if coalesce(v_bal, 0) + r.amount - p_amount < 0 then
      raise exception 'Insufficient balance in account';
    end if;
    update public.accounts
    set current_balance = current_balance + r.amount - p_amount
    where id = r.account_id
      and user_id = v_sub
      and public.workspace_matches(organization_id, p_organization_id);

  elsif r.kind = 'income' then
    update public.accounts
    set current_balance = current_balance + p_amount - r.amount
    where id = r.account_id
      and user_id = v_sub
      and public.workspace_matches(organization_id, p_organization_id);

  elsif r.kind = 'transfer' then
    select upper(trim(coalesce(a.currency_code, '')))
    into v_src_cur
    from public.accounts a
    where a.id = r.account_id
      and a.user_id = v_sub
      and public.workspace_matches(a.organization_id, p_organization_id);

    select upper(trim(coalesce(a.currency_code, '')))
    into v_dst_cur
    from public.accounts a
    where a.id = r.transfer_account_id
      and a.user_id = v_sub
      and public.workspace_matches(a.organization_id, p_organization_id);

    if v_src_cur is null or v_src_cur = '' or v_dst_cur is null or v_dst_cur = '' then
      raise exception 'Transfer account not found';
    end if;

    if v_src_cur <> v_dst_cur
       and (p_transfer_credit_amount is null or p_transfer_credit_amount <= 0) then
      raise exception 'Cross-currency transfer requires a converted destination amount';
    end if;

    v_old_credit := coalesce(r.transfer_credit_amount, r.amount);
    v_new_credit := coalesce(p_transfer_credit_amount, p_amount);
    if v_new_credit <= 0 then
      raise exception 'Invalid transfer credit amount';
    end if;
    select a.current_balance into v_bal
    from public.accounts a
    where a.id = r.account_id
      and a.user_id = v_sub
      and public.workspace_matches(a.organization_id, p_organization_id);
    if coalesce(v_bal, 0) + r.amount - p_amount < 0 then
      raise exception 'Insufficient balance in source account';
    end if;
    select a.current_balance into v_dest_bal
    from public.accounts a
    where a.id = r.transfer_account_id
      and a.user_id = v_sub
      and public.workspace_matches(a.organization_id, p_organization_id);
    if coalesce(v_dest_bal, 0) - v_old_credit + v_new_credit < 0 then
      raise exception 'Insufficient balance in destination account';
    end if;
    update public.accounts
    set current_balance = current_balance + r.amount - p_amount
    where id = r.account_id
      and user_id = v_sub
      and public.workspace_matches(organization_id, p_organization_id);
    update public.accounts
    set current_balance = current_balance - v_old_credit + v_new_credit
    where id = r.transfer_account_id
      and user_id = v_sub
      and public.workspace_matches(organization_id, p_organization_id);
  else
    raise exception 'Invalid transaction kind';
  end if;

  update public.transactions
  set
    amount = p_amount,
    category_id = case when r.kind = 'transfer' then null else p_category_id end,
    note = p_note,
    transfer_credit_amount = case
      when r.kind = 'transfer' then coalesce(p_transfer_credit_amount, p_amount)
      else null
    end
  where id = p_transaction_id
    and user_id = v_sub
    and public.workspace_matches(organization_id, p_organization_id);
end;
$$;
create or replace function public.get_dashboard_summary(
  p_user_id uuid,
  p_organization_id uuid default null
)
returns table (
  total_balance numeric,
  income_month numeric,
  expense_month numeric,
  savings_total numeric
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_sub uuid;
begin
  perform public.assert_workspace_read(p_user_id, p_organization_id);
  v_sub := public.workspace_row_subject_user_id(p_user_id, p_organization_id);

  return query
  with month_bounds as (
    select date_trunc('month', now())::date as month_start
  )
  select
    coalesce((
      select sum(a.current_balance)
      from public.accounts a
      where a.user_id = v_sub
        and public.workspace_matches(a.organization_id, p_organization_id)
        and a.is_archived = false
    ), 0) as total_balance,
    coalesce((
      select sum(t.amount)
      from public.transactions t, month_bounds m
      where t.user_id = v_sub
        and public.workspace_matches(t.organization_id, p_organization_id)
        and t.kind = 'income'
        and t.transaction_date >= m.month_start
    ), 0) as income_month,
    coalesce((
      select sum(t.amount)
      from public.transactions t, month_bounds m
      where t.user_id = v_sub
        and public.workspace_matches(t.organization_id, p_organization_id)
        and t.kind = 'expense'
        and t.transaction_date >= m.month_start
    ), 0) as expense_month,
    coalesce((
      select sum(s.current_amount)
      from public.savings_goals s
      where s.user_id = v_sub
        and public.workspace_matches(s.organization_id, p_organization_id)
    ), 0) as savings_total;
end;
$$;
create or replace function public.delete_account_cascade(
  p_account_id uuid,
  p_organization_id uuid default null
)
returns void
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_user_id uuid;
  r record;
begin
  if auth.uid() is null then
    raise exception 'Not authenticated';
  end if;

  select a.user_id
  into v_user_id
  from public.accounts a
  where a.id = p_account_id
    and public.workspace_matches(a.organization_id, p_organization_id);

  if v_user_id is null then
    raise exception 'Account not found';
  end if;

  if p_organization_id is null then
    if v_user_id <> auth.uid() then
      raise exception 'Forbidden';
    end if;
  elsif public.organization_actor_role(p_organization_id, auth.uid()) not in ('owner', 'co_owner', 'admin') then
    raise exception 'Forbidden';
  end if;

  for r in
    select t.id
    from public.transactions t
    where t.user_id = v_user_id
      and public.workspace_matches(t.organization_id, p_organization_id)
      and (t.account_id = p_account_id or t.transfer_account_id = p_account_id)
  loop
    perform public.delete_transaction_internal(v_user_id, r.id, true, p_organization_id);
  end loop;

  delete from public.recurring_transactions
  where user_id = v_user_id
    and public.workspace_matches(organization_id, p_organization_id)
    and account_id = p_account_id;

  delete from public.bill_reminders
  where user_id = v_user_id
    and public.workspace_matches(organization_id, p_organization_id)
    and account_id = p_account_id;

  with del_contrib as (
    delete from public.savings_goal_contributions c
    where c.user_id = v_user_id
      and public.workspace_matches(c.organization_id, p_organization_id)
      and c.account_id = p_account_id
    returning c.goal_id
  ),
  goals_to_fix as (
    select distinct goal_id from del_contrib
  )
  update public.savings_goals g
  set
    current_amount = coalesce((
      select sum(c2.amount)
      from public.savings_goal_contributions c2
      where c2.goal_id = g.id
    ), 0),
    is_completed = coalesce((
      select sum(c2.amount)
      from public.savings_goal_contributions c2
      where c2.goal_id = g.id
    ), 0) >= g.target_amount
  where g.user_id = v_user_id
    and public.workspace_matches(g.organization_id, p_organization_id)
    and g.id in (select goal_id from goals_to_fix);

  delete from public.loan_payments
  where user_id = v_user_id
    and public.workspace_matches(organization_id, p_organization_id)
    and account_id = p_account_id;

  update public.loans
  set principal_account_id = null
  where user_id = v_user_id
    and public.workspace_matches(organization_id, p_organization_id)
    and principal_account_id = p_account_id;

  delete from public.accounts
  where id = p_account_id
    and user_id = v_user_id
    and public.workspace_matches(organization_id, p_organization_id);
end;
$$;
create or replace function public.add_savings_progress(
  p_user_id uuid,
  p_goal_id uuid,
  p_amount numeric,
  p_account_id uuid,
  p_note text default null,
  p_organization_id uuid default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_sub uuid;
  v_current_balance numeric;
  v_account_currency text;
  v_goal_name text;
  v_goal_current numeric;
  v_goal_target numeric;
  v_goal_currency text;
  v_contribution_id uuid;
  v_tx_id uuid;
begin
  perform public.assert_workspace_access(p_user_id, p_organization_id);
  v_sub := public.workspace_row_subject_user_id(p_user_id, p_organization_id);

  select current_balance, currency_code
  into v_current_balance, v_account_currency
  from public.accounts
  where id = p_account_id
    and user_id = v_sub
    and public.workspace_matches(organization_id, p_organization_id);

  if v_current_balance is null then
    raise exception 'Account not found';
  end if;

  if v_current_balance < p_amount then
    raise exception 'Insufficient balance in selected account';
  end if;

  select name, current_amount, target_amount, currency_code
  into v_goal_name, v_goal_current, v_goal_target, v_goal_currency
  from public.savings_goals
  where id = p_goal_id
    and user_id = v_sub
    and public.workspace_matches(organization_id, p_organization_id);

  if v_goal_name is null then
    raise exception 'Savings goal not found';
  end if;

  if upper(coalesce(v_account_currency, '')) <> upper(coalesce(v_goal_currency, '')) then
    raise exception 'Selected account currency must match savings goal currency';
  end if;

  if (v_goal_current + p_amount) > v_goal_target then
    raise exception 'Amount exceeds remaining savings goal';
  end if;

  update public.accounts
  set current_balance = current_balance - p_amount
  where id = p_account_id
    and user_id = v_sub
    and public.workspace_matches(organization_id, p_organization_id);

  update public.savings_goals
  set current_amount = current_amount + p_amount,
      is_completed = (current_amount + p_amount) >= target_amount
  where id = p_goal_id
    and user_id = v_sub
    and public.workspace_matches(organization_id, p_organization_id);

  insert into public.savings_goal_contributions (
    user_id, organization_id, goal_id, account_id, amount, note
  ) values (
    v_sub, p_organization_id, p_goal_id, p_account_id, p_amount, p_note
  ) returning id into v_contribution_id;

  insert into public.transactions (
    user_id,
    organization_id,
    account_id,
    category_id,
    kind,
    amount,
    source_type,
    source_ref_id,
    note,
    transaction_date,
    transfer_account_id
  ) values (
    v_sub,
    p_organization_id,
    p_account_id,
    null,
    'expense',
    p_amount,
    'savings_contribution',
    v_contribution_id,
    coalesce(p_note, 'Savings contribution: ' || v_goal_name),
    now(),
    null
  ) returning id into v_tx_id;

  update public.savings_goal_contributions
  set transaction_id = v_tx_id
  where id = v_contribution_id;
end;
$$;
create or replace function public.update_savings_goal(
  p_user_id uuid,
  p_goal_id uuid,
  p_name text,
  p_target_amount numeric,
  p_currency_code text,
  p_organization_id uuid default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_sub uuid;
  v_current_amount numeric;
  v_existing_currency text;
begin
  perform public.assert_workspace_access(p_user_id, p_organization_id);
  v_sub := public.workspace_row_subject_user_id(p_user_id, p_organization_id);

  select current_amount, currency_code
  into v_current_amount, v_existing_currency
  from public.savings_goals
  where id = p_goal_id
    and user_id = v_sub
    and public.workspace_matches(organization_id, p_organization_id);

  if v_current_amount is null then
    raise exception 'Savings goal not found';
  end if;

  if p_target_amount <= 0 then
    raise exception 'Target amount must be greater than 0';
  end if;

  if p_target_amount < v_current_amount then
    raise exception 'Target amount cannot be lower than current savings';
  end if;

  if upper(coalesce(v_existing_currency, '')) <> upper(coalesce(p_currency_code, ''))
     and v_current_amount > 0 then
    raise exception 'Cannot change currency for a goal that already has saved funds';
  end if;

  update public.savings_goals
  set name = p_name,
      target_amount = p_target_amount,
      currency_code = upper(p_currency_code),
      is_completed = current_amount >= p_target_amount
  where id = p_goal_id
    and user_id = v_sub
    and public.workspace_matches(organization_id, p_organization_id);
end;
$$;
create or replace function public.refund_savings_progress(
  p_user_id uuid,
  p_goal_id uuid,
  p_amount numeric,
  p_account_id uuid,
  p_note text default null,
  p_organization_id uuid default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_sub uuid;
  v_goal_name text;
  v_goal_current numeric;
  v_goal_currency text;
  v_account_currency text;
  v_contribution_id uuid;
  v_tx_id uuid;
begin
  perform public.assert_workspace_access(p_user_id, p_organization_id);
  v_sub := public.workspace_row_subject_user_id(p_user_id, p_organization_id);

  if p_amount <= 0 then
    raise exception 'Refund amount must be greater than 0';
  end if;

  select name, current_amount, currency_code
  into v_goal_name, v_goal_current, v_goal_currency
  from public.savings_goals
  where id = p_goal_id
    and user_id = v_sub
    and public.workspace_matches(organization_id, p_organization_id);

  if v_goal_name is null then
    raise exception 'Savings goal not found';
  end if;

  if v_goal_current < p_amount then
    raise exception 'Refund amount exceeds current savings';
  end if;

  select currency_code
  into v_account_currency
  from public.accounts
  where id = p_account_id
    and user_id = v_sub
    and public.workspace_matches(organization_id, p_organization_id);

  if v_account_currency is null then
    raise exception 'Account not found';
  end if;

  if upper(coalesce(v_account_currency, '')) <> upper(coalesce(v_goal_currency, '')) then
    raise exception 'Selected account currency must match savings goal currency';
  end if;

  update public.savings_goals
  set current_amount = current_amount - p_amount,
      is_completed = (current_amount - p_amount) >= target_amount
  where id = p_goal_id
    and user_id = v_sub
    and public.workspace_matches(organization_id, p_organization_id);

  update public.accounts
  set current_balance = current_balance + p_amount
  where id = p_account_id
    and user_id = v_sub
    and public.workspace_matches(organization_id, p_organization_id);

  insert into public.savings_goal_contributions (
    user_id, organization_id, goal_id, account_id, amount, note
  ) values (
    v_sub, p_organization_id, p_goal_id, p_account_id, -p_amount, coalesce(p_note, 'Savings refund')
  ) returning id into v_contribution_id;

  insert into public.transactions (
    user_id,
    organization_id,
    account_id,
    category_id,
    kind,
    amount,
    source_type,
    source_ref_id,
    note,
    transaction_date,
    transfer_account_id
  ) values (
    v_sub,
    p_organization_id,
    p_account_id,
    null,
    'income',
    p_amount,
    'savings_refund',
    v_contribution_id,
    coalesce(p_note, 'Savings refund: ' || v_goal_name),
    now(),
    null
  ) returning id into v_tx_id;

  update public.savings_goal_contributions
  set transaction_id = v_tx_id
  where id = v_contribution_id;
end;
$$;
create or replace function public.run_due_recurring_transactions(
  p_user_id uuid,
  p_organization_id uuid default null
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_sub uuid;
  r record;
  v_next_date date;
  v_count integer := 0;
begin
  perform public.assert_workspace_access(p_user_id, p_organization_id);
  v_sub := public.workspace_row_subject_user_id(p_user_id, p_organization_id);

  for r in
    select *
    from public.recurring_transactions
    where user_id = v_sub
      and public.workspace_matches(organization_id, p_organization_id)
      and is_active = true
      and next_run_date <= current_date
    order by next_run_date asc
  loop
    perform public.create_transaction(
      v_sub,
      r.account_id,
      r.category_id,
      r.kind,
      r.amount,
      r.next_run_date::timestamptz,
      coalesce(r.note, 'Recurring transaction'),
      null,
      null,
      p_organization_id
    );

    v_next_date :=
      case r.frequency
        when 'daily' then r.next_run_date + interval '1 day'
        when 'weekly' then r.next_run_date + interval '7 day'
        when 'monthly' then r.next_run_date + interval '1 month'
        when 'yearly' then r.next_run_date + interval '1 year'
      end;

    update public.recurring_transactions
    set next_run_date = v_next_date::date
    where id = r.id
      and user_id = v_sub
      and public.workspace_matches(organization_id, p_organization_id);

    v_count := v_count + 1;
  end loop;

  return v_count;
end;
$$;
create or replace function public.mark_bill_paid(
  p_user_id uuid,
  p_bill_id uuid,
  p_paid_on date default current_date,
  p_organization_id uuid default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_sub uuid;
  r record;
  v_next_due date;
begin
  perform public.assert_workspace_access(p_user_id, p_organization_id);
  v_sub := public.workspace_row_subject_user_id(p_user_id, p_organization_id);

  select *
  into r
  from public.bill_reminders
  where id = p_bill_id
    and user_id = v_sub
    and public.workspace_matches(organization_id, p_organization_id);

  if not found then
    raise exception 'Bill reminder not found';
  end if;

  perform public.create_transaction(
      v_sub,
    r.account_id,
    r.category_id,
    'expense',
    r.amount,
    p_paid_on::timestamptz,
    'Bill paid: ' || r.title,
    null,
    null,
    p_organization_id
  );

  if r.frequency = 'once' then
    update public.bill_reminders
    set is_active = false,
        last_paid_at = now()
    where id = p_bill_id
      and user_id = v_sub
      and public.workspace_matches(organization_id, p_organization_id);
  else
    v_next_due :=
      case r.frequency
        when 'weekly' then r.due_date + interval '7 day'
        when 'monthly' then r.due_date + interval '1 month'
        when 'yearly' then r.due_date + interval '1 year'
      end;

    update public.bill_reminders
    set due_date = v_next_due,
        last_paid_at = now()
    where id = p_bill_id
      and user_id = v_sub
      and public.workspace_matches(organization_id, p_organization_id);
  end if;
end;
$$;
create or replace function public.create_loan(
  p_user_id uuid,
  p_person_name text,
  p_total_amount numeric,
  p_direction text,
  p_currency_code text,
  p_principal_account_id uuid,
  p_due_date date default null,
  p_note text default null,
  p_organization_id uuid default null
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_sub uuid;
  v_id uuid;
  v_acct_currency text;
  v_balance numeric;
  v_tx_note text;
  v_tx_id uuid;
begin
  perform public.assert_workspace_access(p_user_id, p_organization_id);
  v_sub := public.workspace_row_subject_user_id(p_user_id, p_organization_id);

  if p_total_amount is null or p_total_amount <= 0 then
    raise exception 'Total amount must be positive';
  end if;

  if p_person_name is null or length(trim(p_person_name)) = 0 then
    raise exception 'Person name is required';
  end if;

  if p_direction not in ('owed_to_me', 'owed_by_me') then
    raise exception 'Invalid loan direction';
  end if;

  if p_principal_account_id is null then
    raise exception 'Account is required to record loan principal';
  end if;

  select a.currency_code, a.current_balance
  into v_acct_currency, v_balance
  from public.accounts a
  where a.id = p_principal_account_id
    and a.user_id = v_sub
    and public.workspace_matches(a.organization_id, p_organization_id);

  if v_acct_currency is null then
    raise exception 'Account not found';
  end if;

  if upper(trim(coalesce(v_acct_currency, ''))) <>
     upper(trim(coalesce(p_currency_code, ''))) then
    raise exception 'Account currency must match loan currency';
  end if;

  insert into public.loans (
    user_id,
    organization_id,
    person_name,
    total_amount,
    currency_code,
    direction,
    principal_account_id,
    note,
    due_date
  ) values (
    v_sub,
    p_organization_id,
    trim(p_person_name),
    p_total_amount,
    upper(trim(coalesce(p_currency_code, 'USD'))),
    p_direction,
    p_principal_account_id,
    nullif(trim(coalesce(p_note, '')), ''),
    p_due_date
  ) returning id into v_id;

  if p_direction = 'owed_by_me' then
    v_tx_note := coalesce(
      nullif(trim(coalesce(p_note, '')), ''),
      'Loan received — I owe ' || trim(p_person_name)
    );
    v_tx_id := public.create_transaction_internal(
      v_sub,
      p_principal_account_id,
      null,
      'income',
      p_total_amount,
      now(),
      v_tx_note,
      null,
      null,
      'loan_principal',
      v_id,
      p_organization_id
    );
  elsif p_direction = 'owed_to_me' then
    if coalesce(v_balance, 0) < p_total_amount then
      raise exception 'Insufficient balance in selected account for this loan';
    end if;
    v_tx_note := coalesce(
      nullif(trim(coalesce(p_note, '')), ''),
      'Loan given — ' || trim(p_person_name) || ' owes me'
    );
    v_tx_id := public.create_transaction_internal(
      v_sub,
      p_principal_account_id,
      null,
      'expense',
      p_total_amount,
      now(),
      v_tx_note,
      null,
      null,
      'loan_principal',
      v_id,
      p_organization_id
    );
  end if;

  update public.loans
  set principal_transaction_id = v_tx_id
  where id = v_id;

  return v_id;
end;
$$;
create or replace function public.update_loan(
  p_user_id uuid,
  p_loan_id uuid,
  p_person_name text,
  p_total_amount numeric,
  p_direction text,
  p_currency_code text,
  p_due_date date default null,
  p_note text default null,
  p_organization_id uuid default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_sub uuid;
  v_paid_so_far numeric;
  v_existing_direction text;
  v_existing_currency text;
begin
  perform public.assert_workspace_access(p_user_id, p_organization_id);
  v_sub := public.workspace_row_subject_user_id(p_user_id, p_organization_id);

  if p_total_amount <= 0 then
    raise exception 'Total amount must be greater than zero';
  end if;

  select l.direction, upper(trim(coalesce(l.currency_code, '')))
  into v_existing_direction, v_existing_currency
  from public.loans l
  where l.id = p_loan_id
    and l.user_id = v_sub
    and public.workspace_matches(l.organization_id, p_organization_id);

  if v_existing_direction is null then
    raise exception 'Loan not found';
  end if;

  if p_direction <> v_existing_direction then
    raise exception 'Loan direction cannot be changed after creation';
  end if;

  if upper(trim(coalesce(p_currency_code, ''))) <> v_existing_currency then
    raise exception 'Loan currency cannot be changed after creation';
  end if;

  select coalesce(sum(lp.amount), 0)
  into v_paid_so_far
  from public.loan_payments lp
  where lp.loan_id = p_loan_id
    and lp.user_id = v_sub
    and public.workspace_matches(lp.organization_id, p_organization_id);

  if p_total_amount < v_paid_so_far then
    raise exception 'Total amount cannot be lower than paid amount';
  end if;

  update public.loans
  set person_name = p_person_name,
      total_amount = p_total_amount,
      due_date = p_due_date,
      note = p_note
  where id = p_loan_id
    and user_id = v_sub
    and public.workspace_matches(organization_id, p_organization_id);

  if not found then
    raise exception 'Loan not found';
  end if;
end;
$$;
create or replace function public.record_loan_payment(
  p_user_id uuid,
  p_loan_id uuid,
  p_account_id uuid,
  p_amount numeric,
  p_payment_date timestamptz default now(),
  p_note text default null,
  p_organization_id uuid default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_sub uuid;
  v_direction text;
  v_person_name text;
  v_total_amount numeric;
  v_paid_so_far numeric;
  v_kind text;
  v_note text;
  v_payment_id uuid;
  v_tx_id uuid;
begin
  perform public.assert_workspace_access(p_user_id, p_organization_id);
  v_sub := public.workspace_row_subject_user_id(p_user_id, p_organization_id);

  select l.direction, l.person_name, l.total_amount
  into v_direction, v_person_name, v_total_amount
  from public.loans l
  where l.id = p_loan_id
    and l.user_id = v_sub
    and public.workspace_matches(l.organization_id, p_organization_id);

  if v_direction is null then
    raise exception 'Loan not found';
  end if;

  if not exists (
    select 1
    from public.accounts a
    where a.id = p_account_id
      and a.user_id = v_sub
      and public.workspace_matches(a.organization_id, p_organization_id)
  ) then
    raise exception 'Account not found';
  end if;

  select coalesce(sum(lp.amount), 0)
  into v_paid_so_far
  from public.loan_payments lp
  where lp.loan_id = p_loan_id
    and lp.user_id = v_sub
    and public.workspace_matches(lp.organization_id, p_organization_id);

  if p_amount > (v_total_amount - v_paid_so_far) then
    raise exception 'Amount exceeds remaining loan balance';
  end if;

  insert into public.loan_payments (
    user_id, organization_id, loan_id, account_id, amount, payment_date, note
  ) values (
    v_sub,
    p_organization_id,
    p_loan_id,
    p_account_id,
    p_amount,
    (coalesce(p_payment_date, now()) at time zone 'utc')::date,
    p_note
  ) returning id into v_payment_id;

  v_kind := case when v_direction = 'owed_to_me' then 'income' else 'expense' end;
  v_note := coalesce(
    p_note,
    case
      when v_direction = 'owed_to_me' then 'Loan payment received from ' || v_person_name
      else 'Loan payment sent to ' || v_person_name
    end
  );

  v_tx_id := public.create_transaction_internal(
    v_sub,
    p_account_id,
    null,
    v_kind,
    p_amount,
    coalesce(p_payment_date, now()),
    v_note,
    null,
    null,
    'loan_payment',
    v_payment_id,
    p_organization_id
  );

  update public.loan_payments
  set transaction_id = v_tx_id
  where id = v_payment_id;
end;
$$;
create or replace function public.delete_loan_cascade(
  p_loan_id uuid,
  p_organization_id uuid default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid;
  v_tx_id uuid;
begin
  v_user_id := auth.uid();
  if v_user_id is null then
    raise exception 'Unauthorized';
  end if;

  if not exists (
    select 1
    from public.loans l
    where l.id = p_loan_id
      and l.user_id = v_user_id
      and public.workspace_matches(l.organization_id, p_organization_id)
  ) then
    raise exception 'Loan not found';
  end if;

  for v_tx_id in
    select distinct x.id
    from (
      select lp.transaction_id as id
      from public.loan_payments lp
      where lp.loan_id = p_loan_id
        and lp.user_id = v_user_id
        and public.workspace_matches(lp.organization_id, p_organization_id)
        and lp.transaction_id is not null
      union all
      select t.id
      from public.transactions t
      where t.user_id = v_user_id
        and t.source_type = 'loan_payment'
        and public.workspace_matches(t.organization_id, p_organization_id)
        and t.source_ref_id in (
          select lp2.id
          from public.loan_payments lp2
          where lp2.loan_id = p_loan_id
            and lp2.user_id = v_user_id
            and public.workspace_matches(lp2.organization_id, p_organization_id)
        )
      union all
      select l.principal_transaction_id
      from public.loans l
      where l.id = p_loan_id
        and l.user_id = v_user_id
        and public.workspace_matches(l.organization_id, p_organization_id)
        and l.principal_transaction_id is not null
      union all
      select t.id
      from public.transactions t
      where t.user_id = v_user_id
        and t.source_type = 'loan_principal'
        and public.workspace_matches(t.organization_id, p_organization_id)
        and t.source_ref_id = p_loan_id
    ) x
    where x.id is not null
  loop
    if exists (
      select 1
      from public.transactions tr
      where tr.id = v_tx_id
        and tr.user_id = v_user_id
        and public.workspace_matches(tr.organization_id, p_organization_id)
    ) then
      perform public.delete_transaction_internal(
        v_user_id,
        v_tx_id,
        true,
        p_organization_id
      );
    end if;
  end loop;

  delete from public.loan_payments
  where loan_id = p_loan_id
    and user_id = v_user_id
    and public.workspace_matches(organization_id, p_organization_id);

  delete from public.loans
  where id = p_loan_id
    and user_id = v_user_id
    and public.workspace_matches(organization_id, p_organization_id);
end;
$$;
create or replace function public.exchange_account_currency(
  p_user_id uuid,
  p_account_id uuid,
  p_target_currency text,
  p_rate numeric,
  p_organization_id uuid default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_sub uuid;
begin
  perform public.assert_workspace_access(p_user_id, p_organization_id);
  v_sub := public.workspace_row_subject_user_id(p_user_id, p_organization_id);

  if p_rate is null or p_rate <= 0 then
    raise exception 'Invalid exchange rate';
  end if;

  update public.accounts
  set current_balance = round((current_balance * p_rate)::numeric, 2),
      opening_balance = round((opening_balance * p_rate)::numeric, 2),
      currency_code = p_target_currency
  where id = p_account_id
    and user_id = v_sub
    and public.workspace_matches(organization_id, p_organization_id);
end;
$$;
create or replace function public.delete_savings_goal(
  p_user_id uuid,
  p_goal_id uuid,
  p_organization_id uuid default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_current numeric;
  v_sub uuid;
begin
  if auth.uid() is null then
    raise exception 'Unauthorized';
  end if;

  perform public.assert_workspace_access(p_user_id, p_organization_id);
  v_sub := public.workspace_row_subject_user_id(p_user_id, p_organization_id);
  if p_organization_id is not null then
    perform public.assert_org_owner_or_co_owner_may_delete(p_organization_id);
  end if;

  select current_amount
  into v_current
  from public.savings_goals
  where id = p_goal_id
    and user_id = v_sub
    and public.workspace_matches(organization_id, p_organization_id);

  if v_current is null then
    raise exception 'Savings goal not found';
  end if;

  if coalesce(v_current, 0) > 0 then
    raise exception 'Savings goal still has a balance; refund it to an account first';
  end if;

  delete from public.savings_goals
  where id = p_goal_id
    and user_id = v_sub
    and public.workspace_matches(organization_id, p_organization_id);

  if not found then
    raise exception 'Savings goal not found';
  end if;
end;
$$;
